version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_DATABASE: moneymong
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always
