server:
  port: 8080
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${ACTIVE_PROFILE}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    properties:
      format_sql: true
      hibernate.hbm2ddl.auto: create

# actuator 관리
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

# swagger
springdoc:
  packages-to-scan: com.moneymong.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

# Cloud
cloud:
  ncp:
    s3:
      bucket: moneymong
      endpoint: "https://kr.object.ncloudstorage.com"
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
