spring:
  config:
    import: optional:file:.env[.properties]

server:
  port: ${SERVER_PORT}
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
