version: '3'
services:
  db:
    container_name: moneymong-db
    image: mysql
    environment:
      MYSQL_DATABASE: moneymong
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DOCKER_DB_PORT}
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always

  server:
    container_name: server
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - ${DOCKER_SERVER_PORT}
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NCP_ACCESS_KEY: ${NCP_ACCESS_KEY}
      NCP_SECRET_KEY: ${NCP_SECRET_KEY}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_URL: ${DB_URL}
